/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1822ProxiableUpgradeable } from "./IERC1822ProxiableUpgradeable";
export type { IERC1822ProxiableUpgradeable0817 } from "./IERC1822ProxiableUpgradeable0817";
