/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOwnable__factory } from "./IOwnable__factory";
export { IOwnable0817__factory } from "./IOwnable0817__factory";
