/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721Upgradeable0810 } from "./IERC721Upgradeable0810";
export type { IERC721Upgradeable0817 } from "./IERC721Upgradeable0817";
