/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBeacon0817,
  IBeacon0817Interface,
} from "../../IBeacon.sol/IBeacon0817";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBeacon0817__factory {
  static readonly abi = _abi;
  static createInterface(): IBeacon0817Interface {
    return new utils.Interface(_abi) as IBeacon0817Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBeacon0817 {
    return new Contract(address, _abi, signerOrProvider) as IBeacon0817;
  }
}
