/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeacon__factory } from "./IBeacon__factory";
export { IBeacon0817__factory } from "./IBeacon0817__factory";
