/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC1822ProxiableUpgradeable0817,
  IERC1822ProxiableUpgradeable0817Interface,
} from "../../draft-IERC1822Upgradeable.sol/IERC1822ProxiableUpgradeable0817";

const _abi = [
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC1822ProxiableUpgradeable0817__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1822ProxiableUpgradeable0817Interface {
    return new utils.Interface(
      _abi
    ) as IERC1822ProxiableUpgradeable0817Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1822ProxiableUpgradeable0817 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC1822ProxiableUpgradeable0817;
  }
}
