/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DropMetadataRenderer } from "./DropMetadataRenderer";
export type { DropMetadataRenderer0817 } from "./DropMetadataRenderer0817";
