/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FundsReceiver } from "./FundsReceiver";
export type { FundsReceiver0817 } from "./FundsReceiver0817";
