/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwnableSkeleton__factory } from "./OwnableSkeleton__factory";
export { OwnableSkeleton0817__factory } from "./OwnableSkeleton0817__factory";
