/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DropConfigGetter,
  DropConfigGetterInterface,
} from "../../EditionMetadataRenderer.sol/DropConfigGetter";

const _abi = [
  {
    inputs: [],
    name: "config",
    outputs: [
      {
        components: [
          {
            internalType: "contract IMetadataRenderer",
            name: "metadataRenderer",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "editionSize",
            type: "uint64",
          },
          {
            internalType: "uint16",
            name: "royaltyBPS",
            type: "uint16",
          },
          {
            internalType: "address payable",
            name: "fundsRecipient",
            type: "address",
          },
        ],
        internalType: "struct IERC721Drop.Configuration",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class DropConfigGetter__factory {
  static readonly abi = _abi;
  static createInterface(): DropConfigGetterInterface {
    return new utils.Interface(_abi) as DropConfigGetterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DropConfigGetter {
    return new Contract(address, _abi, signerOrProvider) as DropConfigGetter;
  }
}
