/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC2981Upgradeable } from "./IERC2981Upgradeable";
export type { IERC2981Upgradeable0817 } from "./IERC2981Upgradeable0817";
