/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1967Proxy } from "./ERC1967Proxy";
export type { ERC1967Proxy0817 } from "./ERC1967Proxy0817";
