/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnableSkeleton } from "./OwnableSkeleton";
export type { OwnableSkeleton0817 } from "./OwnableSkeleton0817";
