/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1967Upgrade__factory } from "./ERC1967Upgrade__factory";
export { ERC1967Upgrade0817__factory } from "./ERC1967Upgrade0817__factory";
