/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFactoryUpgradeGate__factory } from "./IFactoryUpgradeGate__factory";
export { IFactoryUpgradeGate0817__factory } from "./IFactoryUpgradeGate0817__factory";
