/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZoraFeeManager__factory } from "./IZoraFeeManager__factory";
export { IZoraFeeManager0817__factory } from "./IZoraFeeManager0817__factory";
