/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnableUpgradeable } from "./OwnableUpgradeable";
export type { OwnableUpgradeable0817 } from "./OwnableUpgradeable0817";
