/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Script0810,
  Script0810Interface,
} from "../../Script.sol/Script0810";

const _abi = [
  {
    inputs: [],
    name: "IS_SCRIPT",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vm",
    outputs: [
      {
        internalType: "contract Vm",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Script0810__factory {
  static readonly abi = _abi;
  static createInterface(): Script0810Interface {
    return new utils.Interface(_abi) as Script0810Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Script0810 {
    return new Contract(address, _abi, signerOrProvider) as Script0810;
  }
}
