/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721AUpgradeable0810 } from "./IERC721AUpgradeable0810";
export type { IERC721AUpgradeable0817 } from "./IERC721AUpgradeable0817";
