/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC721AUpgradeable0810__factory } from "./IERC721AUpgradeable0810__factory";
export { IERC721AUpgradeable0817__factory } from "./IERC721AUpgradeable0817__factory";
