/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeaconUpgradeable__factory } from "./IBeaconUpgradeable__factory";
export { IBeaconUpgradeable0817__factory } from "./IBeaconUpgradeable0817__factory";
