/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Proxy__factory } from "./Proxy__factory";
export { Proxy0817__factory } from "./Proxy0817__factory";
