/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OwnableWithConfirmation0810__factory } from "./OwnableWithConfirmation0810__factory";
export { OwnableWithConfirmation0817__factory } from "./OwnableWithConfirmation0817__factory";
