/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeaconUpgradeable } from "./IBeaconUpgradeable";
export type { IBeaconUpgradeable0817 } from "./IBeaconUpgradeable0817";
