/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { IZoraFeeManager, IZoraFeeManagerInterface } from '../IZoraFeeManager'

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
    ],
    name: 'getZORAWithdrawFeesBPS',
    outputs: [
      {
        internalType: 'address payable',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

export class IZoraFeeManager__factory {
  static readonly abi = _abi
  static createInterface(): IZoraFeeManagerInterface {
    return new utils.Interface(_abi) as IZoraFeeManagerInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IZoraFeeManager {
    return new Contract(address, _abi, signerOrProvider) as IZoraFeeManager
  }
}
