export const {
  title,
  description,
  baseUrl,
  chainId,
  contractAddress,
  imageHost,
  imageHostAppend,
  rpcUrl,
  rinkebyRpcUrl,
  launchTime,
  presaleLaunchTime,
  graphqlEndpoint,
} = {
  title: process.env.NEXT_PUBLIC_TITLE,
  decription: process.env.NEXT_PUBLIC_DESCRIPTION,
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL,
  chainId: process.env.NEXT_PUBLIC_CHAIN_ID,
  contractAddress: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS,
  imageHost: process.env.NEXT_PUBLIC_IMAGE_HOST,
  imageHostAppend: process.env.NEXT_PUBLIC_IMAGE_HOST_APPEND,
  rpcUrl: process.env.NEXT_PUBLIC_RPC_URL,
  rinkebyRpcUrl: process.env.NEXT_PUBLIC_RINKEBY_RPC_URL,
  presaleLaunchTime: process.env.NEXT_PUBLIC_PRESALE_LAUNCH_TIME,
  launchTime: process.env.NEXT_PUBLIC_LAUNCH_TIME,
  graphqlEndpoint: process.env.NEXT_PUBLIC_GRAPHQL_URI,
}
