/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DSTest } from "./DSTest";
export type { Test } from "./Test";
export type { StdError } from "./StdError";
export type { StdStorage } from "./StdStorage";
