/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  FundsReceiver0817,
  FundsReceiver0817Interface,
} from "../../FundsReceiver.sol/FundsReceiver0817";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FundsReceived",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607a8061001e6000396000f3fe608060405236603f5760405134815233907f8e47b87b0ef542cdfa1659c551d88bad38aa7f452d2bbb349ab7530dfec8be8f9060200160405180910390a2005b600080fdfea2646970667358221220341c7b18de4cd19331bfe1f796d3e65206b5b6a2c94e9b85cbf5f4044f6505f664736f6c63430008110033";

type FundsReceiver0817ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FundsReceiver0817ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FundsReceiver0817__factory extends ContractFactory {
  constructor(...args: FundsReceiver0817ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FundsReceiver0817> {
    return super.deploy(overrides || {}) as Promise<FundsReceiver0817>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FundsReceiver0817 {
    return super.attach(address) as FundsReceiver0817;
  }
  override connect(signer: Signer): FundsReceiver0817__factory {
    return super.connect(signer) as FundsReceiver0817__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FundsReceiver0817Interface {
    return new utils.Interface(_abi) as FundsReceiver0817Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FundsReceiver0817 {
    return new Contract(address, _abi, signerOrProvider) as FundsReceiver0817;
  }
}
