/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FundsReceiver__factory } from "./FundsReceiver__factory";
export { FundsReceiver0817__factory } from "./FundsReceiver0817__factory";
