/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZoraFeeManager } from "./IZoraFeeManager";
export type { IZoraFeeManager0817 } from "./IZoraFeeManager0817";
