/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MetadataRenderAdminCheck } from "./MetadataRenderAdminCheck";
export type { MetadataRenderAdminCheck0817 } from "./MetadataRenderAdminCheck0817";
