/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981Upgradeable__factory } from "./IERC2981Upgradeable__factory";
export { IERC2981Upgradeable0817__factory } from "./IERC2981Upgradeable0817__factory";
