/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1967UpgradeUpgradeable__factory } from "./ERC1967UpgradeUpgradeable__factory";
export { ERC1967UpgradeUpgradeable0817__factory } from "./ERC1967UpgradeUpgradeable0817__factory";
