/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOperatorFilterRegistry0810 } from "./IOperatorFilterRegistry0810";
export type { IOperatorFilterRegistry0817 } from "./IOperatorFilterRegistry0817";
