/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC165Upgradeable0817,
  ERC165Upgradeable0817Interface,
} from "../../ERC165Upgradeable.sol/ERC165Upgradeable0817";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ERC165Upgradeable0817__factory {
  static readonly abi = _abi;
  static createInterface(): ERC165Upgradeable0817Interface {
    return new utils.Interface(_abi) as ERC165Upgradeable0817Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC165Upgradeable0817 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC165Upgradeable0817;
  }
}
