/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnableWithConfirmation0810 } from "./OwnableWithConfirmation0810";
export type { OwnableWithConfirmation0817 } from "./OwnableWithConfirmation0817";
