/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FactoryUpgradeGate } from "./FactoryUpgradeGate";
export type { FactoryUpgradeGate0817 } from "./FactoryUpgradeGate0817";
