/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721ReceiverUpgradeable } from "./IERC721ReceiverUpgradeable";
export type { IERC721ReceiverUpgradeable0817 } from "./IERC721ReceiverUpgradeable0817";
