/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC721MetadataUpgradeable0810__factory } from "./IERC721MetadataUpgradeable0810__factory";
export { IERC721MetadataUpgradeable0817__factory } from "./IERC721MetadataUpgradeable0817__factory";
